<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-03-06T08:43:50Z" name="Default suite" finished-at="2020-03-06T08:44:07Z" duration-ms="16747">
    <groups>
    </groups>
    <test started-at="2020-03-06T08:43:50Z" name="Default test" finished-at="2020-03-06T08:44:07Z" duration-ms="16747">
      <class name="com.CA.qa.TestCases.APITesting">
        <test-method signature="API_TESTING_with_Automation(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.CA.qa.TestCases.APITesting@68999068]" started-at="2020-03-06T08:43:51Z" name="API_TESTING_with_Automation" data-provider="APIdata" finished-at="2020-03-06T08:44:07Z" duration-ms="16147" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://172.16.15.210/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[CAServices/AgentManualDial.php?api_key=&username=&agentID=&campaignName=&customerNumber=&UCID=&uui=&format=]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[KKfdb819a5c849d829cd000819d4a4463b]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[ca_testing]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[santosh1]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[san_tz_inbound]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[9553578721]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[Test1]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[Json]]>
              </value>
            </param>
            <param index="10">
              <value>
                <![CDATA[yes]]>
              </value>
            </param>
            <param index="11">
              <value>
                <![CDATA[No]]>
              </value>
            </param>
            <param index="12">
              <value>
                <![CDATA[{"ucid":"9189158339772211","status":"queued successfully"}]]>
              </value>
            </param>
            <param index="13">
              <value>
                <![CDATA[{"status":"Agent is not available"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Api not worked expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Api not worked expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.CA.qa.TestCases.APITesting.API_TESTING_with_Automation(APITesting.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_TESTING_with_Automation -->
      </class> <!-- com.CA.qa.TestCases.APITesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
